### ISSUE TITLE
Don't 404 after deleting an Environment 

### ISSUE THREAD

**Issue by desteves** [pulumi/esc#318] opened 2024-05-29 20:34 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

After an ESC Environment is confirmed for deletion via the browser, Pulumi Cloud returns a 404.
<img width="677" alt="image" src="https://github.com/pulumi/esc/assets/2991841/21cc2ad6-7cd5-42be-b2c7-6eb8130194a2">

It'd be a better experience if, instead, we are informed the environment has been deleted and redirected to the main /esc page

**Comment by aacotroneo** [comment] 2024-06-11 19:11
I can't reproduce at the moment. I don't see any direct code fix made recently but there's been some optimizations in subscriptions in that page that might explain the issue (after the env gets deleted, the page might be refreshed before the redirection takes place)

https://github.com/pulumi/esc/assets/10578291/85f00a35-91ac-4afe-82f8-90615022e9cd

I'm closing for now unless we can reproduce.

**Closed by aacotroneo** 2024-06-11 19:11 UTC
Labels: kind/enhancement, resolution/no-repro
