### ISSUE TITLE
Editor view always reports unknown for secrets

### ISSUE THREAD

**Issue by iwahbe** [pulumi/esc#164] opened 2023-11-03 22:18 UTC
### What happened?

I defined an environment with secrets (from `fn::secret`). The preview shows all fields as `[unknown]`, even though they are knowable. Ideally, I would see a fully flushed out object with only secret values redacted. At the very least, the preview should say `[secret]` instead of `[unknown]`.

### Example

https://app.pulumi.com/pulumi/esc/pulumi-cloudflare-testing

### Output of `pulumi about`

NA

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by pgavlin** [comment] 2023-11-03 22:23
@komalali this is a dupe of https://github.com/pulumi/pulumi-service/issues/16162. Would you mind closing that issue as a dupe and using this one to track?

**Comment by komalali** [comment] 2023-11-06 17:17
Hmm.. that one is the one tracked in the iteration and I don't wanna really change a bunch of things around since I'm pretty close to closing it out. I'll just close them both with the PR.

**Closed** 2023-11-07 22:55 UTC
Labels: kind/bug, needs-triage
